openapi: 3.0.1
info:
  title: E-Games API
  description: E-Games API
  version: 1.0.0
servers:
- url: https://1wmbquctgg.execute-api.eu-west-1.amazonaws.com/dev/
tags:
- name: Product
  description: Products
paths:
  /products:
    get:
      tags:
      - Product
      summary: Get all products
      operationId: getProducts
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      tags:
      - Product
      summary: Find product by ID
      description: Returns a single pet
      operationId: getPetById
      parameters:
      - name: id
        in: path
        description: ID of a product to return
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Product not found
          content: {}
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        count:
          type: integer
        description:
          type: string
        price:
          type: integer
        title:
          type: string
      xml:
        name: Product
