openapi: 3.0.1
info:
  title: E-Games API
  description: E-Games API
  version: 1.0.0
servers:
  - url: https://1wmbquctgg.execute-api.eu-west-1.amazonaws.com/dev/
tags:
  - name: Product
    description: Products
paths:
  /products:
    get:
      tags:
        - Product
      summary: Get all products
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
    post:
      tags:
        - Product
      summary: Create new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        201:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
  /products/{id}:
    get:
      tags:
        - Product
      summary: Find product by ID
      description: Returns a single pet
      parameters:
        - name: id
          in: path
          description: ID of a product to return
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        404:
          description: Product not found
          content: {}
components:
  schemas:
    ProductResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        count:
          type: integer
          minimum: 0
        description:
          type: string
          maxLength: 1000
        price:
          type: integer
          minimum: 0
        title:
          type: string
          maxLength: 255
        imgSrc:
          type: string
          maxLength: 500
          description: Link to an image
    NewProduct:
      allOf:
        - $ref: '#/components/schemas/ProductResponse'
        - type: object
          required:
            - title
            - price
            - count
